# This workflow will do a an install of node dependencies, build the
# source code and run tests. Blame Roberto if this Action fails.

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
